### PR TITLE
Switched to expose downloaded archives directly to Docker

### PR DESCRIPTION
**Pull request by szakharchenko**
This makes the build more robust, since the `curl 172.17.0.1` trick is too unreliable.

### CODE REVIEW

**Comment by madduci** [comment]
hi @szakharchenko,

thank you for your contribution, but I have to reject your changes, since I've used in the past the method you are proposing and I've switched from it, because the build size of the final Image will use more than 3 GB in space compared to the actual size.

The `ADD` instructions make it impossible to delete the *.zip files afterwards and increases the number of layers being used.

What is possible is to switch from the  `curl 172.17.0.1` to a proper `curl http://local-python` using docker-compose networking.

**Comment by szakharchenko** [comment]
The use of a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) addresses the possible size increase issue, as is mentioned in the commit message. Only the unpacked and decimated files are copied to the final image. The first build stage is discarded.

```
$ docker images
REPOSITORY                                                    TAG                 IMAGE ID            CREATED             SIZE
docker-wine-msvc                                              16.9-2019           e4bf34fd2657        11 hours ago        12.2GB
```

It isn't exactly the smallest image I have, but I can't compare it to the size of your original image since it doesn't build due to another Docker container running on `172.17.0.1`. What's the size you would expect the image to have?

**Comment by madduci** [comment]
The final image is 8.43GB. As you see, you have an increase of ~50% with your change.

**Comment by madduci** [comment]
close due to inactivity

**Pull request closed without merging**
